### PR TITLE
Reworked need-structure in state

### PR DESCRIPTION
**Pull request by m0ru**
During the work on the location fields, it was necessary to rewrite the sparql-query that pulls the need-rdf. @fkleedorfer suggested to then use the json-ld structure directly in the state without transformation. This pull-request contains that structure update, the resulting refactorings and a minor bug-fixes that happened en passant. Please merge soon, so that the currently developped code uses the new structure. :)

The location picker is currently commented out. Please leave the branch open as I'll continue working on it. :)

### CODE REVIEW

**Comment by m0ru** [comment]
Just found a few components that I had overlooked during refactoring.

**Comment by m0ru** [comment]
Now, that should be it.

**Comment by m0ru** [comment]
See #688 for documentation.

**Comment by fkleedorfer** [comment]
#402 seems to be more of an issue now

**Comment by fkleedorfer** [comment]
#402 seems to be more of an issue now

**Comment by fkleedorfer** [comment]
On PostInfo, the map that is displayed is zoomed out maximally, to the whole world

**Comment by fkleedorfer** [comment]
The feed doesn't show any items:
feed

**Comment by m0ru** [comment]
Reopening doesn't seem to work either as the success-response isn't handled.

**Comment by fkleedorfer** [comment]
During a conversation, when you click 'close connection', the conversation panel and the need (left side) disappear, then reappear after a few seconds. clicking 'close connection' again makes it diappear permanently

**Comment by m0ru** [comment]
The [map bug](https://github.com/researchstudio-sat/webofneeds/pull/732#issuecomment-239412883) occurs when you switch to the post-info page from another page (instead of reloading there). Seems the watch-expression wasn't quite working as expected.

**Comment by m0ru** [comment]
[Ad](https://github.com/researchstudio-sat/webofneeds/pull/732#issuecomment-239412634) #402: I wrote a new handler for selecting timestamps that looks at whether the own need is the receiver or sender and then goes on to pick the send- or received-time. I guess it doesn't work that way, does it? Probably we should change it to check for the node-uri. 

Or change the message-format so there's only one timestamp as we've talked about.

**Comment by quasarchimaere** [comment]
last commit fixed the feed issue

**Pull request merged**
