### PR TITLE
Feat add create to connections view

### LINKED ISSUE #1607: Move "+ New Post" to a card in overview

### LINKED ISSUE #1608: Display create view on right side

### PR DESCRIPTION
**Pull request by sigpie**
This makes the create view obsolete by adding it to the connections view. Fixes #1607, fixes #1608 

When testing, pay attention to the layout in case anything is broken from adding a new button and verify that it's not possible to get to the old create view anymore.

### CODE REVIEW

**Comment by sigpie** [comment]
Also closes #1593

**Comment by fkleedorfer** [comment]
Blocked by #1646

**Comment by fkleedorfer** [comment]
Blocked by #1647

**Comment by fkleedorfer** [comment]
Also, it seems @m0ru asks to consider #1640 for this PR

**Comment by fkleedorfer** [comment]
Ok, we'll merge this now.
Fixing #1646 requires merging #1640, which we'll do in the next feature branch in this story.

**Pull request merged**
