### PR TITLE
Feat  page atomlist

### PR DESCRIPTION
**Pull request by fkleedorfer**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Affected Tests have been added/altered (for bug fixes / features)
- [ ] Docs have been reviewed and added/updated if needed (for bug fixes / features)
- [x] Build was run locally and `mvn install` succeeds

## Pull request type

Please check the type of change your PR introduces:
- [~] Bugfix
- [~] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

A large number of atoms is fetched into the owner webapp server for "What's New/What's Around" cases, then effectively shuffled, filtered by some criteria and only the top N are used, leading to fresh content sometimes missing

## What is the new behavior?

Atoms are fetched in batches of size `limit` , filtered and only if not enough atoms are present, the next batch is fetched

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by fkleedorfer** [comment]
Pushed to integration-test

**Comment by quasarchimaere** [comment]
i am pretty sure that the paged list for "get every atom that has been created after date x" is also not sorted by creation date, but i could be wrong

**Comment by fkleedorfer** [comment]
In this implementation, the creation date is not looked at. the paged list used here is ordered by creation date desc, the implementation just fills up the desired number of atoms, allowing for client-side filtering

**Comment by fkleedorfer** [comment]
Seems to work on integration-test

**Pull request merged**
