### PR TITLE
Feat unified js

### PR DESCRIPTION
**Pull request by m0ru**
Medium.js is capable of being bundled (without extra config) now! This allows us to load bundle directly after the html finishes loading/parsing.

**before:**

loading_landingpage_-_good_3g_-_with_gzip

(see [here](https://github.com/researchstudio-sat/webofneeds/issues/546#issuecomment-327556409) for explanation of the experiment))

**after:**

loading_landingpage_-_good_3g_-_with_gzip_and_bundled_mediumjs

The **1 second spent queuing** for the bundle-download is gone. For some reason the bundle download is faster now but the sign-in request takes a lot longer.

### CODE REVIEW

**Comment by quasarchimaere** [comment]
Can we do some investigation on why the sign in process takes a lot longer now? i think roughly 8 sec for the check isSignedIn is not that great. i would hold off on merging this pull request until further investigation/changes have been made

**Comment by m0ru** [comment]
Hm, it's the second `checkLoginStatus` triggered in `load-action.js:60` (only shortly after the one in `configRouting.js:220`). This is repeatable, even if I remove one or the other request. Theoreticall I could make the function stateful to cache the result until a sign-in/sign-up/sign-out has been done, tough I'd rather avoid that -- maybe there's a better way to avoid the redundant request. My approach to diagnosing would be to print timestamps in `RestUserController.isSignedIn` and checking where the time is lost as the contrast between the two requests is rather stark.

**Comment by m0ru** [comment]
Nvm, it's just chrome-devtools showing bogus. If I log `Date.now() - startTime` when the check succeeds or fails, it takes 670ms.

**Comment by m0ru** [comment]
#1206 gets rid of the redundant request (the first one though, i.e. not the one for which Chrome's measurement breaks ^^")

**Pull request merged**
