### PR TITLE
set up js testing with karma and jasmine:

### PR DESCRIPTION
**Pull request by fkleedorfer**
- add karma configurations for testing our app
- update some angularjs bower dependencies - some were uncompatible
- add simple tests just to see if it works
- add tests for somePromises function from linkedDataService
 -make somePromises function public in order to be able to unit-test it

Note: this brunch is based on dev brunch with unfunctional app! should be merged/rebased as soon as fixed!

### CODE REVIEW

**Comment by fkleedorfer** [comment]
@yanapanchenko can we still merge this?

**Comment by yanapanchenko** [comment]
I will have a look if it will work now after our angular updates - I remember before it was not compatible

**Comment by fkleedorfer** [comment]
@yanapanchenko Any news on this?

**Comment by fkleedorfer** [comment]
dropped

**Pull request closed without merging**
