### PR TITLE
Refac removing unused js deps

### PR DESCRIPTION
**Pull request by m0ru**
Removed the following dependencies:

- angular-bootstrap
- angular-mocks
- angular-ui-utils
- bootstrap
- font-awesome
- jquery
- js-md5
- ng-clip
- ng-scrollbar
- ng-tags-input
- Q

Some of these required minor code-changes, in particular `Q`/`$q` and -- indirectly -- jQuery (apparently angular was using it behind the scenes for `$element.find`)

This reduces the bundle's size by roughly 14kB, which isn't too noticeably to it's 1.4MB, though ^^"

### CODE REVIEW

**Comment by quasarchimaere** [comment]
Please merge master into this branch again to resolve conflicts, also why is the minify set to false in the gulpfile now

**Comment by m0ru** [comment]
Hups, i disabled it for more convenient debugging and accidentally committed the change ^^"

I've fixed that now, and merged master onto this branch.

**Comment by heikofriedrich** [comment]
hashtag-feature that shoes tag in little box in gui when typing #... is not working anymore

**Comment by heikofriedrich** [comment]
still doesnt work on integration test, i dont know why but doesnt work

**Pull request merged**
