### PR TITLE
Fix deletedneed #2577

### LINKED ISSUE #2561: spurious accept option
When you request a chat connection and the counterpart accepts, the GUI looks as if the coutnerpart was requesting a connection.

### LINKED ISSUE #2577: Failed to close "Suggested" connections + Reposts after deleting need
When deleting a need, connections with "ConnectionState": "Suggested" are not closed on remote part.
Also Reposts still exist and can not load and show original content anymore.

requires #1822

### PR DESCRIPTION
**Pull request by quasarchimaere**
requires #2586 

Changes:
- stores Failed uri retrieval within the process-state (either need or connections)
- Refactors all Process relevant states and move it from connections/needs to the process-reducer
- Adapts the connectionHeader to show if a need was not being able to be loaded from the server
-- adds a button to close the connection directly in the conn-list (if the remoteNeed was not retrievable)
- Adapts the postHeader to show if a need was not being able to be loaded from the server
- Adapts square-image to indicate if the post given in the uri was unable to be loaded from the server -> this comes in handy if we have a groupchat and a member deletes their connected need

Fixes #2577 
Fixes #2561 (possible at least)

Also adds little Persona Identicons to square-image)

I think the scope of this PR is reached with the refactoring and given info for deleted (Remote-)Needs, if there is anything else that needs to be checked for failedToLoad then we might adapt this in the future (especially within post-content, post-content-message, post-content-info or post-content-general, as well as suggested-post-picker/viewer)

Please notice the changes made to the state by looking into the `won-owner-webapp/README.md`

Please merge this PullRequest only if we have tested the whole application, due to refactorings i might have broken some parts, add these as comments to this PR, i will try and fix them or give helpful advice in the meantime

### CODE REVIEW

**Comment by fkleedorfer** [comment]
@quasarchimaere Please resolve conflicts

**Comment by quasarchimaere** [comment]
@fkleedorfer will do first thing tomorrow

**Comment by quasarchimaere** [comment]
currently blocked trying to fix issue #2561 within this PR

**Comment by quasarchimaere** [comment]
closing this until further notice

**Comment by sigpie** [comment]
Direct responses to a deleted need keep showing the icon and title of the deleted need in their details. A placeholder stating that the need in question was deleted would be more appropriate.

**Comment by quasarchimaere** [comment]
> Direct responses to a deleted need keep showing the icon and title of the deleted need in their details. A placeholder stating that the need in question was deleted would be more appropriate.

this seems to be a minor issue, we should create a ticket for that and handle this in a smaller PR

**Comment by sigpie** [comment]
Styling inconsistency: 

space_differences

Both buttons should have an equal amount of space around them.

**Comment by quasarchimaere** [comment]
> Styling inconsistency:
> 
> space_differences
> 
> Both buttons should have an equal amount of space around them.

noted, not going to change this though

**Pull request merged**
