### PR TITLE
Feat mail config

### PR DESCRIPTION
**Pull request by yanapanchenko**
Enabled only for integration-test deployment, see corresponding environment setup in jenkins. Not siutable for production deployment because for now it is the simplest mail functionality implementation, e.g. it doesn't verify the user really possesses the email account he/she provides.

To receive email notifications when working on integration-test deployment of WoN:
1. Provide you real email when signing-up to the owner app.
2. In the OLD owner gui, after creating a need, click need's "Settings", select the checkboxes for "Email notifications" and click on "Set notifications" button.
3. After that all the corresponding notifications (about new matches, requests, conversation messages) should always be sent to the email address the user signed in with. To see it at work, send e.g. 'connect' command to the DebugBot connection for the need set up at (2).

### CODE REVIEW

**Comment by yanapanchenko** [comment]
Now also enabled for devel and master deployments

**Comment by yanapanchenko** [comment]
Now by default notifications about received requests (connect) and conversations (connection message) are sent to the user's email.

**Comment by m0ru** [comment]
yay :)

last change: can we change the link titles into something more human readable? See below for examples. If possible the links at the bottom of these should visually be a button in the style of the new app. Dunno how much inline-css is allowed in emails though.

## Requests - before

Dear User,

You have received a new Conversation Request for your posting <https://satsrv04.researchstudio.at:8082/owner/rework.html#/post/owner/info?myUri=https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000>. Please visit <https://satsrv04.researchstudio.at:8082/owner/rework.html#/post/visitor/messages/?myUri=https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000&theirUri=https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45> to view it in detail.

Sincerely yours,
Owner application team

## Requests - after

Hi there,

The person behind “[Moved to Vienna, need new couch](https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45)” wants to contact [you](https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000). They wrote: <blockquote>Hi there! I really like the shade of green on the couch you posted. :3</blockquote>

[[Click here to pick up the conversation]](https://satsrv04.researchstudio.at:8082/owner/rework.html#/post/visitor/messages/?myUri=https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000&theirUri=https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45).

Best Wishes,
Owner application team

## Matches

Hi there,

The post “[Moved to Vienna, need new couch](https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45)”  might be interesting for [you](https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000).

[[Click here to request a conversation]](https://satsrv04.researchstudio.at:8082/owner/rework.html#/post/visitor/messages/?myUri=https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000&theirUri=https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45).

Best Wishes,
Owner application team

## Conversation messages

Hi there,

The person behind “[Moved to Vienna, need new couch](https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45)”  has send [you](https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000) a message. They wrote: <blockquote>Nice. I could pick it up tommorow at ten! :) </blockquote>

[[Click here to answer them]](https://satsrv04.researchstudio.at:8082/owner/rework.html#/post/visitor/messages/?myUri=https://satsrv04.researchstudio.at:8889/won/resource/need/1699468782503723000&theirUri=https://satsrv05.researchstudio.at:8889/won/resource/need/onp8g95e2wq1bpmpmg45).

Best Wishes,
Owner application team

**Comment by yanapanchenko** [comment]
It is possible to use html template instead of text template - then the uris can be hidden behind clickable text. About putting need title in the text - we cannot do it without accessing the linked data, the information we have is only the message itself. Do we want to access the node for the need's data at that point? Need to talk to @fkleedorfer about that.

**Comment by yanapanchenko** [comment]
Decided to merge for now, and create a separate issue for producing html-based emails.

**Pull request merged**
