### PR TITLE
Feat  replace router

### PR DESCRIPTION
**Pull request by quasarchimaere**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Affected Tests have been added/altered (for bug fixes / features)
- [ ] Docs have been reviewed and added/updated if needed (for bug fixes / features)
- [ ] Build was run locally and `mvn install` succeeds

## Pull request type

Please check the type of change your PR introduces:
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

- Fixes: N/A

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by fkleedorfer** [comment]
Bug (?): with this PR, creating an atom using only default values is not possible. One has to make at least one modification, otherwise the `publish` button is deactivated. Is that intended?

**Comment by quasarchimaere** [comment]
seems to be a bug, will adapt that before this pr is ready to review, thx for the bugreport

**Comment by fkleedorfer** [comment]
On the phone, can't get from the conversation detail view back to the chats overview via the 'chats'  button in the menu. I have to click on another menu button (e.g. 'Create'), which does what is expected, and then use the menu -> 'chats' button again to get to the chats overview.

**Comment by fkleedorfer** [comment]
Images are not displayed correctly for personas.
grafik

**Comment by fkleedorfer** [comment]
Post as persona not working in this PR - after posting the atom is not held by the persona. Adding the persona later does work, though.

**Comment by quasarchimaere** [comment]
closing this PR -> changes were made in a different branch/pr see #3248

**Pull request closed without merging**
