### PR TITLE
Fix jumping columns #1729

### LINKED ISSUE #1729: Columns "jumping" when post subtitle is too long
When the post subtitle is too long (e.g. "Post (no matching context specified)", it get's wrapped next to the connection indicators. As the indicators disappear when the post is opened, the text gets unwrapped and the columns "jump" to adjust to the new width.

post_closed
post_open

### PR DESCRIPTION
**Pull request by quasarchimaere**
fixes the "jumping" columns by also abbreviating the subtitle in favor of breaking into multiple lines

fixes #1729

### CODE REVIEW

**Comment by peacememories** [comment]
The original issue does not seem to be completely resolved:

image
image

The overview column changes size drastically when folding and unfolding needs.

**Comment by quasarchimaere** [comment]
should be resolved due to a min-width of the list in the non mobile view

**Comment by peacememories** [comment]
The jumping is fixed, but while animating the "Show Post Details" button button is cut off on the right:
image
Also the horizontal padding jumps slightly when hitting the responsiveness breakpoint.

**Comment by peacememories** [comment]
Moving the remaining problem to a separate issue and merging this.

**Pull request merged**
