### PR TITLE
Avoid hint for inactive needs

### PR DESCRIPTION
**Pull request by fkleedorfer**
Check the state of the need before sending hint.
issue #1271
(cherry picked from commit e394948)

### CODE REVIEW

**Comment by maxstolze** [comment]
Is not working with the LastSeenNeedsMatcherApp

**Comment by maxstolze** [comment]
Maybe it is possible to set the "MatchingBehavior" entry to "DoNotMatch" when we close a need to make sure there are no more hints coming from the node for the current need. And when we reopen a need, we set it back to "Mutual".

**Comment by quasarchimaere** [comment]
@maxstolze, this approach is not going to be possible, the problem with this approach is that the changing the behaviour in the need-document would result in a loss of information of the previous matchingbehaviour state, we would have to add an additional previousMatchingBehaviour to the document to ensure that we can restore the previous state, or we would need to crawl through all the messages/events to reconstruct what the state was which in this case would mean that we would have to have unnecessary calculations for those edge cases.

However maybe we need to adapt the matcher in a way that it will not consider closed/inactive needs for matching, this is the most feasible approach as we already parse some need-information for matching anyway (e.g. matchingBehaviour)

**Comment by maxstolze** [comment]
@quasarchimaere +1

**Comment by heikofriedrich** [comment]
what we gonna do with this pull request now? who is working on that?

**Pull request merged**
