### PR TITLE
Bumped n3 version to 1.0.0-beta.1

### PR DESCRIPTION
**Pull request by peacememories**
Contains fixes for https://github.com/rdfjs/N3.js/issues/135 and https://github.com/rdfjs/N3.js/issues/136

This allows us to minify function names again, and makes it possible to use synchronous parsers in the future.

### CODE REVIEW

**Comment by quasarchimaere** [comment]
i would not merge this pr for now because the version number seems to be a bit fidgety and could cause problems if devs have different versions of the lib, we should rather fix it to the latest version that we know exists and continuously update it

**Comment by peacememories** [comment]
The version number we have right now is `1.0.0-alpha` so I don’t think the new version is more fidgety

**Comment by m0ru** [comment]
^ what he says

The reason for bumping to 1.0.0 in the first place was, that it uses the new rdf-js standard for serialising data, which substantially improves interop between the different rdf-related libraries we use.

**Comment by quasarchimaere** [comment]
oh i didnt mean that i am not ok with the version in general, i just meant that we should just remove the ^ prefix from the version number, since we had issues with different versions on different build systems in the past and this is a pita to find and fix if it occurs

**Comment by m0ru** [comment]
aaaah, lol, sure ^^

**Comment by quasarchimaere** [comment]
wait why was this pr merged with the fluent versioning of the dependency now?

**Comment by peacememories** [comment]
This may not have been communicated clearly:

With the newer npm versions we have access to package locking now. The
`package-lock.json` specifies the fixed versions of every package (even
transitive dependencies) we use and makes sure that on an `npm install`
those exact versions get installed. So there is no need anymore to specify
fixed dependencies in our `package.json`, and since version ranges are the
default result of `nom install <package>` and give us the ability to do
guided updating I recommend we stick with that.
There might already be an issue open to convert all dependencies to range
dependencies.

**Pull request merged**
