### PR TITLE
Feat typescript

### PR DESCRIPTION
**Pull request by m0ru**
We can now use types in our project \o/ :D

Still need to teach intellij to use the same compiler as the project though.

Note: Merge the other pull-request first. I basedthis one off of #1128 (the only open pull-request atm), to avoid any merge-conflicts.

### CODE REVIEW

**Comment by quasarchimaere** [comment]
it seems that the pull request is not working -> it always shows the connection lost "header"

**Comment by m0ru** [comment]
have you run a full `mvn clean` and `mvn install`? (the typescript compiler is a new dependency)

**Comment by m0ru** [comment]
hm, the compiler/linter intellij uses seems to run on different/stricter defaults than our project (it builds via gulp, but intellij highlights a lot of things as compiler-errors)

**Comment by m0ru** [comment]
Apparently `typings` has been deprecated in favour of `npm install @types/pkgname`. Gotta find out how well this plays together with `jspm` (at the worst case we'll have to align versions, as we would have with typings)

**Comment by m0ru** [comment]
Also, the typesystem doesn't seem to take hold, when compiling via gulp/jspm. I can put the following in our app_jspm and it still compiles:
```
function foo(bar: string) {
    console.log(bar);
}
foo(123)
```

**Comment by quasarchimaere** [comment]
i opened it again since the problem was not lying in this pull request and the underlying issue is already fixed

**Comment by quasarchimaere** [comment]
after creating a debug need the console shows the following error:
event-reducer.ts:138 Uncaught (in promise) TypeError: Cannot read property 'uri' of undefined
    at event-reducer.ts:138
    at fb (immutable.js:2527)
    at fb (immutable.js:2536)
    at La.updateIn (immutable.js:1843)
    at La.update (immutable.js:1835)
    at c (event-reducer.ts:138)
    at g (redux-utils.ts:66)
    at redux-utils.ts:67
    at immutable.js:1942
    at Ra.iterate (immutable.js:2309)
    at Oa.iterate.Pa.iterate (immutable.js:2302)
(anonymous)	@	event-reducer.ts:138
fb	@	immutable.js:2527
fb	@	immutable.js:2536
La.updateIn	@	immutable.js:1843
La.update	@	immutable.js:1835
c	@	event-reducer.ts:138
g	@	redux-utils.ts:66
(anonymous)	@	redux-utils.ts:67
(anonymous)	@	immutable.js:1942
Ra.iterate	@	immutable.js:2309
Oa.iterate.Pa.iterate	@	immutable.js:2302
Oa.iterate.Pa.iterate	@	immutable.js:2302
La.__iterate	@	immutable.js:1940
forEach	@	immutable.js:4358
(anonymous)	@	redux-utils.ts:60
(anonymous)	@	index.js:14
(anonymous)	@	index.js:13
b	@	configRedux.ts:16
k	@	createStore.js:180
(anonymous)	@	digestMiddleware.js:10
(anonymous)	@	index.js:13
(anonymous)	@	router-middleware.js:43
dispatch	@	applyMiddleware.js:35
(anonymous)	@	messages-actions.ts:313

**Comment by quasarchimaere** [comment]
after login these errors occur:
WARNING: Tried to load angular more than once.
messaging-agent.ts:36 Starting messaging agent.
login.ts:84 lic4dbg loginVisible:  false false
/owner/rest/users/isSignedIn Failed to load resource: the server responded with a status of 401 (Unauthorized)
utils.ts:371 Uncaught (in promise) Error: Unauthorized
    at z (utils.ts:371)
    at <anonymous>
/owner/rest/users/isSignedIn Failed to load resource: the server responded with a status of 401 (Unauthorized)
connection-reducer.ts:164 invalid or empty connectionsToStore:  undefined
e @ connection-reducer.ts:164
sockjs.js:284 Opening transport: websocket  url:https://satvm05.researchstudio.at/owner/msg/503/gpt7t2ei  RTO:3093
(unknown) WebSocket connection to 'wss://satvm05.researchstudio.at/owner/msg/503/gpt7t2ei/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
WrappedWebSocket
sockjs.js:284 Closed transport: websocket SimpleEvent(type=close, code=1006, reason=WebSocket connection broken, wasClean=false)
sockjs.js:284 Opening transport: xhr-streaming  url:https://satvm05.researchstudio.at/owner/msg/503/sl6i28f6  RTO:3093
login.ts:84 lic4dbg loginVisible:  false false
/owner/rest/users/isSignedIn Failed to load resource: the server responded with a status of 401 (Unauthorized)
utils.ts:371 Uncaught (in promise) Error: Unauthorized
    at z (utils.ts:371)
    at <anonymous>
sockjs.js:284 Closed transport: xhr-streaming SimpleEvent(type=close, code=2007, reason=Transport timeouted, wasClean=false)
sockjs.js:284 Opening transport: xhr-polling  url:https://satvm05.researchstudio.at/owner/msg/503/4gv836rg  RTO:3093
user-reducer.ts:26 reducers.js: received successful-login action from app-server
connection-reducer.ts:164 invalid or empty connectionsToStore:  La
e @ connection-reducer.ts:164
messaging-agent.ts:328 messaging-agent.js: Resetting web-socket connection
messaging-agent.ts:351 messaging-agent.js: websocket closed cleanly. reconnectAttempts =  0
login.ts:84 lic4dbg loginVisible:  false false
sockjs.js:284 Opening transport: websocket  url:https://satvm05.researchstudio.at/owner/msg/385/vky1cj09  RTO:231
(unknown) WebSocket connection to 'wss://satvm05.researchstudio.at/owner/msg/385/vky1cj09/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
WrappedWebSocket
app.bundle.js:43 Closed transport: websocket SimpleEvent(type=close, code=1006, reason=WebSocket connection broken, wasClean=false)
app.bundle.js:43 Opening transport: xhr-streaming  url:https://satvm05.researchstudio.at/owner/msg/385/wkt74uek  RTO:231
app.bundle.js:43 Closed transport: xhr-streaming SimpleEvent(type=close, code=2007, reason=Transport timeouted, wasClean=false)
app.bundle.js:43 Opening transport: xhr-polling  url:https://satvm05.researchstudio.at/owner/msg/385/f6el95yz  RTO:231

**Comment by m0ru** [comment]
Will be postponed until either [the issue with jspm-typescript](https://github.com/jspm/jspm-cli/issues/2323) is fixed or we decide to use webpack.

**Pull request closed without merging**
