### PR TITLE
Bump npm version

### PR DESCRIPTION
**Pull request by peacememories**
npm is now version `next` because `latest` seems to be in a broken state right now: https://github.com/npm/npm/issues/19989

also bumped `node-sass` version because the old version did not have binaries for the new node version: https://github.com/sass/node-sass/issues/2360

This will need a `mvn install` to correctly update the node version.

Also, this might surface a problem with `windows-build-tools` not being installed on developer machines (namely, Python).

Documentation on how to solve this can be found [here](https://github.com/researchstudio-sat/webofneeds/blob/8ba0270affcd265db028bd639db875c3bca08489/documentation/installation-setting-up-frontend-development-environment.md#installing-windows-build-tools-on-windows)

### CODE REVIEW

**Comment by heikofriedrich** [comment]
i get maven build error:
``
[ERROR] gyp ERR! build error 
[ERROR] gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
[ERROR] gyp ERR! stack     at ChildProcess.onExit (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
[ERROR] gyp ERR! System Windows_NT 10.0.15063
[ERROR] gyp ERR! command "C:\\DATA\\DEV\\workspace\\webofneeds\\webofneeds\\won-owner-webapp\\src\\main\\webapp\\node\\node.exe" "C:\\DATA\\DEV\\workspace\\webofneeds\\webofneeds\\won-owner-webapp\\src\\main\\webapp\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[ERROR] gyp ERR! cwd C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rdf-canonize
[ERROR] gyp ERR! node -v v10.1.0
[ERROR] gyp ERR! node-gyp -v v3.6.2
[ERROR] gyp ERR! not ok 
[WARNING] npm WARN won-owner-webapp@0.2.0 No description
[WARNING] npm WARN won-owner-webapp@0.2.0 No repository field.
[WARNING] npm WARN won-owner-webapp@0.2.0 No license field.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! rdf-canonize@0.2.4 install: `node-gyp rebuild`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the rdf-canonize@0.2.4 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\hfriedrich\AppData\Roaming\npm-cache\_logs\2018-05-11T10_12_20_871Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Web of Needs Main .................................. SUCCESS [  0.349 s]
[INFO] Core ............................................... SUCCESS [ 11.269 s]
[INFO] Facet Modules ...................................... SUCCESS [  0.003 s]
[INFO] Facets: Transactions ............................... SUCCESS [  0.931 s]
[INFO] Cryptography ....................................... SUCCESS [  3.976 s]
[INFO] Node ............................................... SUCCESS [  4.640 s]
[INFO] Node Webapp ........................................ SUCCESS [  5.852 s]
[INFO] Utilities .......................................... SUCCESS [  0.001 s]
[INFO] Utilities-Goals .................................... SUCCESS [  2.061 s]
[INFO] Utilities Conversation ............................. SUCCESS [  6.310 s]
[INFO] Owner .............................................. SUCCESS [  2.592 s]
[INFO] Matcher Client ..................................... SUCCESS [  1.809 s]
[INFO] Utilities-Mail ..................................... SUCCESS [  0.862 s]
[INFO] Owner Webapp ....................................... FAILURE [02:24 min]
[INFO] Matcher Utils ...................................... SKIPPED
[INFO] Matcher Service .................................... SKIPPED
[INFO] Bot ................................................ SKIPPED
[INFO] won-matcher-solr ................................... SKIPPED
[INFO] Matcher-Rescal ..................................... SKIPPED
[INFO] Ontology Validator ................................. SKIPPED
[INFO] Utilities-Import ................................... SKIPPED
[INFO] Utilities-Crawling ................................. SKIPPED
[INFO] Vocabulary ......................................... SKIPPED
[INFO] Docker ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:05 min
[INFO] Finished at: 2018-05-11T12:12:20+02:00
[INFO] Final Memory: 224M/923M
[INFO] ------------------------------------------------------------------------
``

**Comment by peacememories** [comment]
@heikofriedrich This error occurs when the `windows-build-tools` are not installed on the system. They contain Python and an MSVC compiler, which are needed to compile native dependencies (like `rdf-canonize` in our case). On your system Python seems to be installed, but not MSVC.

You can read [the instructions](https://github.com/nodejs/node-gyp#on-windows) for installing the build tools on windows.
Note, however, that our current security setup does not allow installation of `windows-build-tools` normally, so [Option 1](https://github.com/nodejs/node-gyp#option-1) is very hacky to setup on our systems.
So I would suggest [Option 2](https://github.com/nodejs/node-gyp#option-2), especially since the Python part seems to already be working on your system.

**Comment by heikofriedrich** [comment]
i tried option 2 (first suboption: Option 1: Install Visual C++ Build Tools using the Default Install option.) => installed Visual Studio Community 2017 => Entwicklung für die universelle Windows-Plattform

Got new error:

```
[INFO] C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rdf-canonize>if not defined npm_config_node_gyp (node "C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
[INFO] Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
[INFO] C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rdf-canonize\build\urdna2015.vcxproj(20,3): error MSB4019: Das importierte Projekt "C:\Microsoft.Cpp.Default.props" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datentr�ger vorhanden ist.
[ERROR] gyp ERR! build error 
[ERROR] gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
[ERROR] gyp ERR! stack     at ChildProcess.onExit (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
[ERROR] gyp ERR! System Windows_NT 10.0.15063
[ERROR] gyp ERR! command "C:\\DATA\\DEV\\workspace\\webofneeds\\webofneeds\\won-owner-webapp\\src\\main\\webapp\\node\\node.exe" "C:\\DATA\\DEV\\workspace\\webofneeds\\webofneeds\\won-owner-webapp\\src\\main\\webapp\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[ERROR] gyp ERR! cwd C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\rdf-canonize
[ERROR] gyp ERR! node -v v10.1.0
[ERROR] gyp ERR! node-gyp -v v3.6.2
[ERROR] gyp ERR! not ok 
[WARNING] npm WARN rollback Rolling back node-pre-gyp@0.9.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\fsevents\node_modules'
[WARNING] npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN won-owner-webapp@0.2.0 No description
[WARNING] npm WARN won-owner-webapp@0.2.0 No repository field.
[WARNING] npm WARN won-owner-webapp@0.2.0 No license field.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! rdf-canonize@0.2.4 install: `node-gyp rebuild`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the rdf-canonize@0.2.4 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     C:\Users\hfriedrich\AppData\Roaming\npm-cache\_logs\2018-05-11T12_51_46_339Z-debug.log
```

**Comment by heikofriedrich** [comment]
got other build error:

> [INFO] ERROR in ./style/won.scss
> [INFO] Module build failed: ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\vendor'
> [INFO]     at Object.fs.readdirSync (fs.js:875:3)
> [INFO]     at Object.getInstalledBinaries (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\extensions.js:129:13)
> [INFO]     at foundBinariesList (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\errors.js:20:15)
> [INFO]     at foundBinaries (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\errors.js:15:5)
> [INFO]     at Object.module.exports.missingBinary (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\errors.js:45:5)
> [INFO]     at module.exports (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\binding.js:15:30)
> [INFO]     at Object.<anonymous> (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\index.js:14:35)
> [INFO]     at Module._compile (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
> [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [INFO]     at Module.load (internal/modules/cjs/loader.js:589:32)
> [INFO]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [INFO]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [INFO]     at Module.require (internal/modules/cjs/loader.js:626:17)
> [INFO]     at require (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
> [INFO]     at Object.<anonymous> (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\sass-loader\lib\loader.js:3:14)
> [INFO]     at Module._compile (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
> [INFO]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [INFO]     at Module.load (internal/modules/cjs/loader.js:589:32)
> [INFO]     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [INFO]     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [INFO]     at Module.require (internal/modules/cjs/loader.js:626:17)
> [INFO]     at require (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
> [INFO]     at loadLoader (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\loadLoader.js:13:17)
> [INFO]     at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
> [INFO]     at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
> [INFO]     at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:173:18
> [INFO]     at loadLoader (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\loadLoader.js:36:3)
> [INFO]     at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
> [INFO]     at runLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
> [INFO]     at NormalModule.doBuild (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:235:3)
> [INFO]     at NormalModule.build (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:365:15)
> [INFO]     at Compilation.buildModule (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\Compilation.js:362:10)
> [INFO]     at moduleFactory.create (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\Compilation.js:711:12)
> [INFO]     at factory (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
> [INFO]     at hooks.afterResolve.callAsync (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
> [INFO]     at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
> [INFO]     at runLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:252:20)
> [INFO]     at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:364:11
> [INFO]     at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:170:18
> [INFO]     at loadLoader (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\loadLoader.js:27:11)
> [INFO]     at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
> [INFO]     at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
> [INFO]     at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:173:18
> [INFO]     at loadLoader (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\loadLoader.js:36:3)
> [INFO]     at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
> [INFO]     at runLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
> [INFO]     at NormalModule.doBuild (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:235:3)
> [INFO]     at NormalModule.build (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:365:15)
> [INFO]     at Compilation.buildModule (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\Compilation.js:362:10)
> [INFO]     at moduleFactory.create (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\Compilation.js:711:12)
> [INFO]     at factory (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
> [INFO]     at hooks.afterResolve.callAsync (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
> [INFO]     at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
> [INFO]     at AsyncSeriesWaterfallHook.lazyCompileHook [as _callAsync] (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\tapable\lib\Hook.js:35:21)
> [INFO]     at resolver (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:126:29)
> [INFO]     at process.nextTick (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:304:9)
> [INFO]     at process._tickCallback (internal/process/next_tick.js:61:11)
> [INFO]  @ ./app/app_webpack.js 5:0-28
> [INFO] Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--6-1!node_modules/sass-loader/lib/loader.js??ref--6-2!style/won.scss:
> [INFO]     Entrypoint mini-css-extract-plugin = *
> [INFO]     [0] ./node_modules/css-loader??ref--6-1!./node_modules/sass-loader/lib/loader.js??ref--6-2!./style/won.scss 5.04 KiB {0} [built] [failed] [1 error]
> [INFO]     
> [INFO]     ERROR in ./style/won.scss (./node_modules/css-loader??ref--6-1!./node_modules/sass-loader/lib/loader.js??ref--6-2!./style/won.scss)
> [INFO]     Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\vendor'
> [INFO]         at Object.fs.readdirSync (fs.js:875:3)
> [INFO]         at Object.getInstalledBinaries (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\extensions.js:129:13)
> [INFO]         at foundBinariesList (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\errors.js:20:15)
> [INFO]         at foundBinaries (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\errors.js:15:5)
> [INFO]         at Object.module.exports.missingBinary (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\errors.js:45:5)
> [INFO]         at module.exports (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\binding.js:15:30)
> [INFO]         at Object.<anonymous> (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\node-sass\lib\index.js:14:35)
> [INFO]         at Module._compile (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
> [INFO]         at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [INFO]         at Module.load (internal/modules/cjs/loader.js:589:32)
> [INFO]         at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [INFO]         at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [INFO]         at Module.require (internal/modules/cjs/loader.js:626:17)
> [INFO]         at require (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
> [INFO]         at Object.<anonymous> (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\sass-loader\lib\loader.js:3:14)
> [INFO]         at Module._compile (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
> [INFO]         at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
> [INFO]         at Module.load (internal/modules/cjs/loader.js:589:32)
> [INFO]         at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
> [INFO]         at Function.Module._load (internal/modules/cjs/loader.js:520:3)
> [INFO]         at Module.require (internal/modules/cjs/loader.js:626:17)
> [INFO]         at require (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
> [INFO]         at loadLoader (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\loadLoader.js:13:17)
> [INFO]         at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
> [INFO]         at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
> [INFO]         at C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:173:18
> [INFO]         at loadLoader (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\loadLoader.js:36:3)
> [INFO]         at iteratePitchingLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
> [INFO]         at runLoaders (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
> [INFO]         at NormalModule.doBuild (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:235:3)
> [INFO]         at NormalModule.build (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModule.js:365:15)
> [INFO]         at Compilation.buildModule (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\Compilation.js:362:10)
> [INFO]         at moduleFactory.create (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\Compilation.js:711:12)
> [INFO]         at factory (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:366:6)
> [INFO]         at hooks.afterResolve.callAsync (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\webpack\lib\NormalModuleFactory.js:143:13)
> [INFO]         at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\DATA\DEV\workspace\webofneeds\webofneeds\won-owner-webapp\src\main\webapp\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
> [ERROR] npm ERR! code ELIFECYCLE
> [ERROR] npm ERR! errno 2
> [ERROR] npm ERR! won-owner-webapp@0.2.0 build: `webpack`
> [ERROR] npm ERR! Exit status 2
> [ERROR] npm ERR! 
> [ERROR] npm ERR! Failed at the won-owner-webapp@0.2.0 build script.
> [ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [ERROR] 
> [ERROR] npm ERR! A complete log of this run can be found in:
> [ERROR] npm ERR!     C:\Users\hfriedrich\AppData\Roaming\npm-cache\_logs\2018-05-11T13_57_15_636Z-debug.log

**Comment by heikofriedrich** [comment]
working now, i will approve if you add this setup to the documentation setup for developers

**Comment by peacememories** [comment]
@heikofriedrich done, see https://github.com/researchstudio-sat/webofneeds/pull/1743/commits/42eb0553a2381a79c299671c5a5ea07a1c580d6c

**Comment by quasarchimaere** [comment]
@heikofriedrich @maxstolze and me all tried to update our build environment and it works for all of us so far so we can merge this pullrequest

**Pull request merged**
