### PR TITLE
Feat updates and bundling

### PR DESCRIPTION
**Pull request by m0ru**
This. is. Angular one-point-foooooouuur!

Update finished. Bundling left to set up.

### CODE REVIEW

**Comment by m0ru** [comment]
Bug fixed. Iterating over maps in angular 1.4 now works like the following: 

```html
<div ng-repeat="(key, value) in myObj"> ... </div>
```

**Comment by m0ru** [comment]
SCSS build working.

**Comment by yanapanchenko** [comment]
going to the detail-view of the need results no need displayed and the error in the console:
Error: [$injector:unpr] Unknown provider: mapServiceProvider <- mapService <- PostDetailCtrl
http://errors.angularjs.org/1.4.1/$injector/unpr?p0=mapServiceProvider%20%3C-%20mapService%20%3C-%20PostDetailCtrl

**Comment by m0ru** [comment]
Javascript fun-time: rdf_store.js was overwriting window.process(.plattform). This is why we don't like global vars. Exactly this.

**Pull request merged**
