### PR TITLE
Allow delete post

### LINKED ISSUE #1822: Need/Post Delete

### PR DESCRIPTION
**Pull request by maxstolze**
Delete need data

Resolves #1822 
Next Steps:
Issue #2548 #2549 #2569

### CODE REVIEW

**Comment by maxstolze** [comment]
Blocked by #2548 #2549

**Comment by quasarchimaere** [comment]
Blocked by #2580 (should not take too long though)

**Comment by maxstolze** [comment]
All issues are now implemented. No more blocking issues.
Resolves: #2548 #2549 #2569  #2580

**Comment by sigpie** [comment]
Exception when the Need of an ad hoc response need gets deleted (need shown is an ad hoc response, the "unloaded" need it responds to was deleted)

adhoc_deleted

**Comment by maxstolze** [comment]
Will be fixed in #2577

**Comment by sigpie** [comment]
What's New and What's Around needs can be archived, but don't show up as archived needs. Because of this, they become inaccessible via the GUI and can't be deleted by the user.

**Pull request merged**
