### PR TITLE
Fix message references

### PR DESCRIPTION
**Pull request by fkleedorfer**
improved and documented the message referencing rules

### CODE REVIEW

**Comment by fkleedorfer** [comment]
@m0ru this will help your work on message ordering in the owner webapp

**Comment by m0ru** [comment]
Ran into an exception when trying to deploy: https://gist.github.com/m0ru/d8a3744de14110c912042002a6202cd4 

I reimported the maven config and rebuild everything before. Are there any config-changes necessary?

**Comment by fkleedorfer** [comment]
I don't think so, but a mvn clean is probably a good idea.

**Comment by m0ru** [comment]
Yep, that fixed it ^^"

**Pull request merged**
