### PR TITLE
Ontology refactoring

### PR DESCRIPTION
**Pull request by fkleedorfer**
Many classes, properties and individuals from the [core](https://w3id.org/won/core) namespace are put into [content](https://w3id.org/won/content), [matching](https://w3id.org/won/matching), and [ext/demo](https://w3id.org/won/ext/demo). 

A number of properties that were used in the webapp but never defined have been added to the appropriate ontologies. A few names were changed as well:

- `won:hasSearchString` -> `match:searchString`
- `won:hasFile` -> `con:file`
- `won:hasPetriNet` -> `con:petriNet`
- `won:hasBpmnWorkflow` -> `con:bpmnWorkflow`
- `won:hasImage` -> `con:image`
- `won:hasText` -> `con:text`
- `won:suggestPostUri` -> `con:suggestedAtom`
- `won:responseToUri` -> `con:inResponseTo`
- `won:forResource` -> `con:feedbackTarget`

The `won:location` property was deleted

EDIT: fixed SearchString -> searchString and cnt:feedbackTarget -> con:feedbackTarget

### CODE REVIEW

**Comment by quasarchimaere** [comment]
cnt:feedbackTarget also trying to figure out what cnt means i know con: means content but not sure about the cnt... anyhow i am not sure if the owner webapp changes are all valid, e.g. occurences of won:image and won:file, can you provide us with an actual list of changed attributes (it seems like the one in the pr description is not representing all the renamings) just so we can make sure if any of the old names is still referenced via hardcoded string or referenced from a won.js constant, we had trouble with the GroupSocket in the last renaming cycle as not every occurence was changed from won.WON.GroupFacet to won.SOCKET.GroupSocket it only changed to won.WON.GroupSocket, so maybe there is a problem if the renaming involves both the prefix and name... (e.g afaik won:hasFile should turn into con:file but in the webapp it is only renamed to won:file)

**Comment by quasarchimaere** [comment]
also why is match:SearchString starting with a upper case letter but con:bpmnWorkflow for example isnt, i get that classes/types start with upper case but afaik this isnt one

**Comment by fkleedorfer** [comment]
Oops.. that line should have read
- `won:forResource` -> `con:feedbackTarget`

**Comment by fkleedorfer** [comment]
Here are the replacements:
```
won:Bad --> con:Bad
won:BinaryRating --> con:BinaryRating
won:BoundingBox --> con:BoundingBox
won:DirectResponse --> con:DirectResponse
won:Feedback --> con:Feedback
won:Good --> con:Good
won:ServiceBot --> con:ServiceBot
won:binaryRating --> con:binaryRating
won:boundingBox --> con:boundingBox
won:hasBpmnWorkflow --> con:bpmnWorkflow
won:feedback --> con:feedback
won:forResource --> con:feedbackTarget
won:hasFile --> con:file
won:geoSpatial --> con:geoSpatial
won:hasImage --> con:image
won:responseToUri --> con:inResponseTo
won:northWestCorner --> con:northWestCorner
won:hasPetriNet --> con:petriNet
won:southEastCorner --> con:southEastCorner
won:suggestPostUri --> con:suggestedAtom
won:tag --> con:tag
won:textMessage --> con:text
won:travelAction --> con:travelAction
https://w3id.org/won/core#Bad --> https://w3id.org/won/content#Bad
https://w3id.org/won/core#BinaryRating --> https://w3id.org/won/content#BinaryRating
https://w3id.org/won/core#BoundingBox --> https://w3id.org/won/content#BoundingBox
https://w3id.org/won/core#DirectResponse --> https://w3id.org/won/content#DirectResponse
https://w3id.org/won/core#Feedback --> https://w3id.org/won/content#Feedback
https://w3id.org/won/core#Good --> https://w3id.org/won/content#Good
https://w3id.org/won/core#ServiceBot --> https://w3id.org/won/content#ServiceBot
https://w3id.org/won/core#binaryRating --> https://w3id.org/won/content#binaryRating
https://w3id.org/won/core#boundingBox --> https://w3id.org/won/content#boundingBox
https://w3id.org/won/core#hasBpmnWorkflow --> https://w3id.org/won/content#bpmnWorkflow
https://w3id.org/won/core#feedback --> https://w3id.org/won/content#feedback
https://w3id.org/won/core#forResource --> https://w3id.org/won/content#feedbackTarget
https://w3id.org/won/core#hasFile --> https://w3id.org/won/content#file
https://w3id.org/won/core#geoSpatial --> https://w3id.org/won/content#geoSpatial
https://w3id.org/won/core#hasImage --> https://w3id.org/won/content#image
https://w3id.org/won/core#responseToUri --> https://w3id.org/won/content#inResponseTo
https://w3id.org/won/core#northWestCorner --> https://w3id.org/won/content#northWestCorner
https://w3id.org/won/core#hasPetriNet --> https://w3id.org/won/content#petriNet
https://w3id.org/won/core#southEastCorner --> https://w3id.org/won/content#southEastCorner
https://w3id.org/won/core#suggestPostUri --> https://w3id.org/won/content#suggestedAtom
https://w3id.org/won/core#tag --> https://w3id.org/won/content#tag
https://w3id.org/won/core#textMessage --> https://w3id.org/won/content#text
https://w3id.org/won/core#travelAction --> https://w3id.org/won/content#travelAction
WON.Bad --> WONCON.Bad
WON.BinaryRating --> WONCON.BinaryRating
WON.BoundingBox --> WONCON.BoundingBox
WON.DirectResponse --> WONCON.DirectResponse
WON.Feedback --> WONCON.Feedback
WON.Good --> WONCON.Good
WON.ServiceBot --> WONCON.ServiceBot
WON.binaryRating --> WONCON.binaryRating
WON.boundingBox --> WONCON.boundingBox
WON.hasBpmnWorkflow --> WONCON.bpmnWorkflow
WON.feedback --> WONCON.feedback
WON.forResource --> WONCON.feedbackTarget
WON.hasFile --> WONCON.file
WON.geoSpatial --> WONCON.geoSpatial
WON.hasImage --> WONCON.image
WON.responseToUri --> WONCON.inResponseTo
WON.northWestCorner --> WONCON.northWestCorner
WON.hasPetriNet --> WONCON.petriNet
WON.southEastCorner --> WONCON.southEastCorner
WON.suggestPostUri --> WONCON.suggestedAtom
WON.tag --> WONCON.tag
WON.textMessage --> WONCON.text
WON.travelAction --> WONCON.travelAction
WON.BadCompacted --> WONCON.BadCompacted
WON.BinaryRatingCompacted --> WONCON.BinaryRatingCompacted
WON.BoundingBoxCompacted --> WONCON.BoundingBoxCompacted
WON.DirectResponseCompacted --> WONCON.DirectResponseCompacted
WON.FeedbackCompacted --> WONCON.FeedbackCompacted
WON.GoodCompacted --> WONCON.GoodCompacted
WON.ServiceBotCompacted --> WONCON.ServiceBotCompacted
WON.binaryRatingCompacted --> WONCON.binaryRatingCompacted
WON.boundingBoxCompacted --> WONCON.boundingBoxCompacted
WON.hasBpmnWorkflowCompacted --> WONCON.bpmnWorkflowCompacted
WON.feedbackCompacted --> WONCON.feedbackCompacted
WON.forResourceCompacted --> WONCON.feedbackTargetCompacted
WON.hasFileCompacted --> WONCON.fileCompacted
WON.geoSpatialCompacted --> WONCON.geoSpatialCompacted
WON.hasImageCompacted --> WONCON.imageCompacted
WON.responseToUriCompacted --> WONCON.inResponseToCompacted
WON.northWestCornerCompacted --> WONCON.northWestCornerCompacted
WON.hasPetriNetCompacted --> WONCON.petriNetCompacted
WON.southEastCornerCompacted --> WONCON.southEastCornerCompacted
WON.suggestPostUriCompacted --> WONCON.suggestedAtomCompacted
WON.tagCompacted --> WONCON.tagCompacted
WON.textMessageCompacted --> WONCON.textCompacted
WON.travelActionCompacted --> WONCON.travelActionCompacted
won:CounterpartSpecification --> match:CounterpartSpecification
won:Flag --> match:Flag
won:NoHintForCounterpart --> match:NoHintForCounterpart
won:NoHintForMe --> match:NoHintForMe
won:UsedForTesting --> match:UsedForTesting
won:WhatsAround --> match:WhatsAround
won:WhatsNew --> match:WhatsNew
won:doNotMatchAfter --> match:doNotMatchAfter
won:doNotMatchBefore --> match:doNotMatchBefore
won:flag --> match:flag
won:matchingContext --> match:matchingContext
won:searchString --> match:searchString
won:seeks --> match:seeks
won:sparqlQuery --> match:sparqlQuery
https://w3id.org/won/core#CounterpartSpecification --> https://w3id.org/won/matching#CounterpartSpecification
https://w3id.org/won/core#Flag --> https://w3id.org/won/matching#Flag
https://w3id.org/won/core#NoHintForCounterpart --> https://w3id.org/won/matching#NoHintForCounterpart
https://w3id.org/won/core#NoHintForMe --> https://w3id.org/won/matching#NoHintForMe
https://w3id.org/won/core#UsedForTesting --> https://w3id.org/won/matching#UsedForTesting
https://w3id.org/won/core#WhatsAround --> https://w3id.org/won/matching#WhatsAround
https://w3id.org/won/core#WhatsNew --> https://w3id.org/won/matching#WhatsNew
https://w3id.org/won/core#doNotMatchAfter --> https://w3id.org/won/matching#doNotMatchAfter
https://w3id.org/won/core#doNotMatchBefore --> https://w3id.org/won/matching#doNotMatchBefore
https://w3id.org/won/core#flag --> https://w3id.org/won/matching#flag
https://w3id.org/won/core#matchingContext --> https://w3id.org/won/matching#matchingContext
https://w3id.org/won/core#searchString --> https://w3id.org/won/matching#searchString
https://w3id.org/won/core#seeks --> https://w3id.org/won/matching#seeks
https://w3id.org/won/core#sparqlQuery --> https://w3id.org/won/matching#sparqlQuery
WON.CounterpartSpecification --> WONMATCH.CounterpartSpecification
WON.Flag --> WONMATCH.Flag
WON.NoHintForCounterpart --> WONMATCH.NoHintForCounterpart
WON.NoHintForMe --> WONMATCH.NoHintForMe
WON.UsedForTesting --> WONMATCH.UsedForTesting
WON.WhatsAround --> WONMATCH.WhatsAround
WON.WhatsNew --> WONMATCH.WhatsNew
WON.doNotMatchAfter --> WONMATCH.doNotMatchAfter
WON.doNotMatchBefore --> WONMATCH.doNotMatchBefore
WON.flag --> WONMATCH.flag
WON.matchingContext --> WONMATCH.matchingContext
WON.searchString --> WONMATCH.searchString
WON.seeks --> WONMATCH.seeks
WON.sparqlQuery --> WONMATCH.sparqlQuery
WON.CounterpartSpecificationCompacted --> WONMATCH.CounterpartSpecificationCompacted
WON.FlagCompacted --> WONMATCH.FlagCompacted
WON.NoHintForCounterpartCompacted --> WONMATCH.NoHintForCounterpartCompacted
WON.NoHintForMeCompacted --> WONMATCH.NoHintForMeCompacted
WON.UsedForTestingCompacted --> WONMATCH.UsedForTestingCompacted
WON.WhatsAroundCompacted --> WONMATCH.WhatsAroundCompacted
WON.WhatsNewCompacted --> WONMATCH.WhatsNewCompacted
WON.doNotMatchAfterCompacted --> WONMATCH.doNotMatchAfterCompacted
WON.doNotMatchBeforeCompacted --> WONMATCH.doNotMatchBeforeCompacted
WON.flagCompacted --> WONMATCH.flagCompacted
WON.matchingContextCompacted --> WONMATCH.matchingContextCompacted
WON.searchStringCompacted --> WONMATCH.searchStringCompacted
WON.seeksCompacted --> WONMATCH.seeksCompacted
WON.sparqlQueryCompacted --> WONMATCH.sparqlQueryCompacted
won:genre --> demo:genre
won:instrument --> demo:instrument
won:AfterParty --> demo:AfterParty
won:Breakfast --> demo:Breakfast
won:Complaint --> demo:Complaint
won:ConsortiumOffer --> demo:ConsortiumOffer
won:ConsortiumSearch --> demo:ConsortiumSearch
won:HandleComplaint --> demo:HandleComplaint
won:Interest --> demo:Interest
won:Meetup --> demo:Meetup
won:Musician --> demo:Musician
won:PaymentServiceRequest --> demo:PaymentServiceRequest
won:PersonalTransportSearch --> demo:PersonalTransportSearch
won:PhdPosition --> demo:PhdPosition
won:PhdPositionSearch --> demo:PhdPositionSearch
won:PostDocPosition --> demo:PostDocPosition
won:PostDocSearch --> demo:PostDocSearch
won:RealEstateRentDemand --> demo:RealEstateRentDemand
won:RealEstateRentOffer --> demo:RealEstateRentOffer
won:RehearsalRoomRentDemand --> demo:RehearsalRoomRentDemand
won:RehearsalRoomRentOffer --> demo:RehearsalRoomRentOffer
won:SightSeeing --> demo:SightSeeing
https://w3id.org/won/core#genre --> https://w3id.org/won/ext/demo#genre
https://w3id.org/won/core#instrument --> https://w3id.org/won/ext/demo#instrument
https://w3id.org/won/core#AfterParty --> https://w3id.org/won/ext/demo#AfterParty
https://w3id.org/won/core#Breakfast --> https://w3id.org/won/ext/demo#Breakfast
https://w3id.org/won/core#Complaint --> https://w3id.org/won/ext/demo#Complaint
https://w3id.org/won/core#ConsortiumOffer --> https://w3id.org/won/ext/demo#ConsortiumOffer
https://w3id.org/won/core#ConsortiumSearch --> https://w3id.org/won/ext/demo#ConsortiumSearch
https://w3id.org/won/core#HandleComplaint --> https://w3id.org/won/ext/demo#HandleComplaint
https://w3id.org/won/core#Interest --> https://w3id.org/won/ext/demo#Interest
https://w3id.org/won/core#Meetup --> https://w3id.org/won/ext/demo#Meetup
https://w3id.org/won/core#Musician --> https://w3id.org/won/ext/demo#Musician
https://w3id.org/won/core#PaymentServiceRequest --> https://w3id.org/won/ext/demo#PaymentServiceRequest
https://w3id.org/won/core#PersonalTransportSearch --> https://w3id.org/won/ext/demo#PersonalTransportSearch
https://w3id.org/won/core#PhdPosition --> https://w3id.org/won/ext/demo#PhdPosition
https://w3id.org/won/core#PhdPositionSearch --> https://w3id.org/won/ext/demo#PhdPositionSearch
https://w3id.org/won/core#PostDocPosition --> https://w3id.org/won/ext/demo#PostDocPosition
https://w3id.org/won/core#PostDocSearch --> https://w3id.org/won/ext/demo#PostDocSearch
https://w3id.org/won/core#RealEstateRentDemand --> https://w3id.org/won/ext/demo#RealEstateRentDemand
https://w3id.org/won/core#RealEstateRentOffer --> https://w3id.org/won/ext/demo#RealEstateRentOffer
https://w3id.org/won/core#RehearsalRoomRentDemand --> https://w3id.org/won/ext/demo#RehearsalRoomRentDemand
https://w3id.org/won/core#RehearsalRoomRentOffer --> https://w3id.org/won/ext/demo#RehearsalRoomRentOffer
https://w3id.org/won/core#SightSeeing --> https://w3id.org/won/ext/demo#SightSeeing

```

**Comment by quasarchimaere** [comment]
does not work:
- first trial failed when creating needs, claiming that the "con" prefix is unknown, happens when trying to create any atom whose usecase generates a query -> probably because `prefixesInPath` doesn't contain the "con" prefix,

Fix this please:
- probably fixed when looking for `prefixesInPath` (within the usecase definitions) and adding the missing/new ontology prefixes

**Pull request merged**
