### PR TITLE
Feat store connection state and (own) facettype in redux-state onload #2823

### LINKED ISSUE #2823: Save facets/connectionstate to reduxState when storing the uris
requires #2800

Now that we retrieve the connectionState as well as the facets directly within the connectionContainer, we can add the additional data directly into the rdf store and thus can enhance the performance of (initial)load or login by prioritizing and/or omitting retrieval of connections based on the additional information

This also allows us to remove the somewhat odd ui quirks where connections inLoading show up as skeletons but disappear after the connection was loaded

### PR DESCRIPTION
**Pull request by quasarchimaere**
blocked by #2800 

this pr stores the connection state and the (own) facet(type) of each connection directly after retrieving the connection container, this makes it easier to reload or prioritize loading by connectionstate and/or facet

fixes #2823

### CODE REVIEW

**Comment by fkleedorfer** [comment]
... i.e. we can now tackle #2800?

**Comment by quasarchimaere** [comment]
yes?

**Comment by fkleedorfer** [comment]
blocked by #2840

**Comment by quasarchimaere** [comment]
closing this PR in favor of #2841

**Pull request closed without merging**
