### PR TITLE
Feat less cluttered post content

### PR DESCRIPTION
**Pull request by sigpie**
Contributes to #2599 

Hides Facets, Flags, Matching Context and some Type details by default. All information is shown if `showRdf` is enabled, as most of this information is only needed for debugging purposes or power users.

### CODE REVIEW

**Comment by quasarchimaere** [comment]
i would not merge this, some facets (eg groupfacet) and some flags (matchingflags) as well as the matchingContext are very valuable information... not only to the developer but also to the user, i agree that we might want to reduce the clutter by hiding some of the content but we should not hide it in general, we might also be able to find better labels for the items

**Comment by sigpie** [comment]
As far as I can tell, there's two flags and one facet that might be of interest for users:

* No Hints for counterpart - maybe show this as "Invisible"
* No Hints for me - maybe show this as "No Matches"
* Group Facet - maybe show this as "Group Chat enabled"

Are there any other flags that should be always visible?

**Comment by sigpie** [comment]
Force-pushed after rebasing on current master.

**Comment by sigpie** [comment]
Changed behaviour to include matching context, group chat facet and "No hint for..." flags.

**Pull request merged**
